### ISSUE TITLE
Documentat Starter Content Plugin

### ISSUE THREAD

**Issue by vladolaru** [pixelgrade/starter_content_exporter#7]
Vei documenta in readme-ul repo-ului modul de functionare a flow-ului de starter de content (in engleza).

De la ce poate sa faca, ce nu poate, care sunt limitarile, in ce situatii, pana la pasii de urmat pentru a oferi starter content pentru o tema.

**Comment by andreilupu** [comment]
Am pus un readme mai detaliat, poti sa arunci o privire?

**Comment by vladolaru** [comment]
E bine @andreilupu
